print("Welcome to the tip calculator.")
bill = float(input("What was the total bill? "))
tip = int(input("What percentage would you like to give? 10, 12 or 15? "))
people = int(input("How many people to split the bill? "))
result = "{:.2f}".format((bill * (1+tip/100)) / people)
print(f"Each person should pay: ${result}")
